USE ROLE SYSADMIN;
USE DATABASE SFDEMO1;
USE SCHEMA PUBLIC;
DROP TABLE IF EXISTS FACT_ORDERS;

CREATE TABLE IF NOT EXISTS FACT_ORDERS 
(ORDER_ID  NUMBER,
  ORDER_DATE DATE,
PURCHASING_COUNTRY_CODE VARCHAR,
SALES_REVENUE FLOAT);

CREATE TABLE IF NOT EXISTS DIM_GEO ( COUNTRY_CODE VARCHAR,COUNTRY_NAME VARCHAR, SUB_REGION VARCHAR, REGION VARCHAR);

CREATE TABLE IF NOT EXISTS DATA_SECURITY_TABLE (
RESTRICTION_LEVEL VARCHAR,
USERNAME VARCHAR,
FIRST_NAME VARCHAR,
LAST_NAME VARCHAR,
DATA_RESTRICTION VARCHAR );

USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE SFDEMO1 TO ROLE ANALYST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SFDEMO1 TO ROLE ANALYST_ROLE;
GRANT ROLE ANALYST_ROLE TO ROLE  SYSADMIN;
 
GRANT SELECT ON ALL TABLES IN SCHEMA SFDEMO1.PUBLIC TO  ROLE ANALYST_ROLE;
GRANT SELECT ON   FUTURE TABLES IN SCHEMA  SFDEMO1.PUBLIC  TO ROLE ANALYST_ROLE;

CREATE USER if not exists  HP_DEV PASSWORD ='HPDEV11';
CREATE USER if not exists NITEO_TEST PASSWORD = 'NITEO_TEST';
CREATE USER if not exists BSATO PASSWORD = 'NITEO_TEST';
CREATE USER if not exists STRAN PASSWORD = 'NITEO_TEST';
CREATE USER if not exists MCHAN PASSWORD = 'NITEO_TEST';

GRANT ROLE ANALYST_ROLE TO USER HP_DEV;
GRANT ROLE ANALYST_ROLE TO USER NITEO_TEST;
GRANT ROLE ANALYST_ROLE TO USER BSATO;
GRANT ROLE ANALYST_ROLE TO USER STRAN;
GRANT ROLE ANALYST_ROLE TO USER MCHAN;
