USE ROLE ACCOUNTADMIN;

-- create necessary database objects
CREATE DATABASE IF NOT EXISTS PRODUCTION;
CREATE ROLE IF NOT EXISTS KAFKA_CONNECT_ROLE;
USE DATABASE PRODUCTION;
CREATE SCHEMA IF NOT EXISTS PRODUCTION.KAFKA_CONNECT_SCHEMA;
CREATE TABLE KAFKA_TABLE_IN(RECORD_METADATA VARIANT,RECORD_CONTENT VARIANT);

-- create necessary grants
GRANT USAGE ON DATABASE PRODUCTION TO KAFKA_CONNECT_ROLE;
GRANT USAGE ON SCHEMA PRODUCTION.KAFKA_CONNECT_SCHEMA TO ROLE KAFKA_CONNECT_ROLE;
GRANT CREATE TABLE ON SCHEMA PRODUCTION.KAFKA_CONNECT_SCHEMA TO ROLE KAFKA_CONNECT_ROLE;
GRANT CREATE STAGE ON SCHEMA PRODUCTION.KAFKA_CONNECT_SCHEMA TO ROLE KAFKA_CONNECT_ROLE;
GRANT CREATE PIPE ON SCHEMA PRODUCTION.KAFKA_CONNECT_SCHEMA TO ROLE KAFKA_CONNECT_ROLE;
GRANT OWNERSHIP ON TABLE KAFKA_TABLE_IN TO ROLE KAFKA_CONNECT_ROLE;

GRANT ROLE KAFKA_CONNECT_ROLE TO USER SSHARMA;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE KAFKA_CONNECT_ROLE;

ALTER USER SSHARMA set DEFAULT_ROLE=KAFKA_CONNECT_ROLE;
ALTER USER SSHARMA SET DEFAULT_WAREHOUSE=COMPUTE_WH;
ALTER USER SSHARMA SET DEFAULT_NAMESPACE=PRODUCTION;
