https://docs.snowflake.com/en/user-guide/security-access-control-configure.html#label-security-role-hierarchy

USE ROLE SECURITYADMIN or higher role;

CREATE ROLE CUSTOM COMMENT = 'This role has all privileges on schema_1';
GRANT USAGE ON DATABASE DATABASE_A TO ROLE CUSTOM;
GRANT ALL ON SCHEMA DATABASE_A.SCHEMA_1 TO ROLE CUSTOM;
GRANT FUTURE

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE CUSTOM;
GRANT ROLE CUSTOM TO ROLE SYSADMIN;

ALTER USER BSMITH SET DISABLED=TRUE;
GRANT ROLE CUSTOM TO USER BSMITH;
ALTER USER BSMITH SET DEFAULT_ROLE = CUSTOM;
ALTER USER BSMITH SET DISABLED=FALSE;

