USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS SSHARMA PASSWORD='CLNAEREP1';

USE ROLE SECURITYADMIN;
GRANT ROLE SYSADMIN TO USER SSHARMA;

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION   RBS3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::742158182529:role/test-external-role'
STORAGE_ALLOWED_LOCATIONS = ("s3://rb-cognos-report-output/");

GRANT USAGE ON INTEGRATION RBS3_INT TO ROLE SYSADMIN;

--create database
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS SFDEMO1;
USE DATABASE SFDEMO1;

CREATE SCHEMA IF NOT EXISTS TARGET;

USE SCHEMA PUBLIC;
--create table

USE SCHEMA PUBLIC;
--create table
CREATE TABLE IF NOT EXISTS PUBLIC.IT_SYSTEMS_OPER_METRICS (
TRANS_ID          NUMBER(18),
APPLICATION_ID    NUMBEr(18),
DATE_CREATED    TIMESTAMP_LTZ,
MONTH_NAME      VARCHAR(12),
TIME_HOUR       NUMBER,
HTTPD           NUMBER,
COGNOS_CGI      NUMBER,
TCP             NUMBER,
BIBUS           NUMBER,
PPDSWEB        NUMBER,
ICS_USERS      NUMBER,
SESSIONS       NUMBER,
FREE_MEMORY    NUMBER,
CM_CURRENT_HEAP  VARCHAR(10),
DISP_CURRENT_HEAP   VARCHAR(10),
DISKSPACE         VARCHAR(150));


-- create the file format for csv without any headers
CREATE OR REPLACE FILE FORMAT "SFDEMO1"."PUBLIC".MYCSV  COMPRESSION = 'AUTO' FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n' SKIP_HEADER = 0 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE'
TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' ESCAPE_UNENCLOSED_FIELD = '\134'
DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');

-- create target schema and create the table.
USE SCHEMA TARGET;

CREATE OR REPLACE TABLE TARGET.IT_SYSTEMS_OPER_METRICS (
TRANS_ID          NUMBER(18),
APPLICATION_ID    NUMBEr(18),
DATE_CREATED    TIMESTAMP_LTZ,
MONTH_NAME      VARCHAR(12),
TIME_HOUR       NUMBER,
HTTPD           NUMBER,
COGNOS_CGI      NUMBER,
TCP             NUMBER,
BIBUS           NUMBER,
PPDSWEB        NUMBER,
ICS_USERS      NUMBER,
SESSIONS      NUMBER,
FREE_MEMORY            NUMBER,
CM_CURRENT_HEAP         VARCHAR(10),
DISP_CURRENT_HEAP      VARCHAR(10),
DISKSPACE         VARCHAR(150));


--create stage
USE SCHEMA PUBLIC;
CREATE OR REPLACE STAGE  SFDEMO1.PUBLIC.RB_EXTERNAL_S3_STAGE_USING_INT_OBJECT
STORAGE_INTEGRATION = RBS3_INT
URL = 's3://rb-cognos-report-output/'
FILE_FORMAT = SFDEMO1.PUBLIC.MYCSV;

--list files
list @RB_EXTERNAL_S3_STAGE_USING_INT_OBJECT/notes;
list @RB_EXTERNAL_S3_STAGE_USING_INT_OBJECT/data;
select t.$1,t.$2 from @RB_EXTERNAL_S3_STAGE_USING_INT_OBJECT/data t
