USE DATABASE CRM_DB;
USE SCHEMA PUBLIC;
CREATE OR REPLACE FILE FORMAT MYCSV 
TYPE = CSV
FIELD_DELIMITER=','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER=1
null_if = ('NULL', 'null')
EMPTY_FIELD_AS_NULL = TRUE;

