
USE ROLE SECURITYADMIN;

/*--create role */
CREATE OR REPLACE ROLE CRM_ANALYST_ROLE COMMENT='CRM_ANALYST_ROLE';
GRANT ROLE CRM_ANALYST_ROLE TO ROLE SYSADMIN;


CREATE OR REPLACE USER CRM_ANALYST  PASSWORD='TCRMSNOW123' 
    DEFAULT_ROLE=CRM_ANALYST_ROLE
    DEFAULT_WAREHOUSE=CRM_WH
    DEFAULT_NAMESPACE=CRB_DB_PUBLIC
    MUST_CHANGE_PASSWORD=FALSE
    COMMENT = 'CRM ANALYST';

GRANT ROLE CRM_ANALYST_ROLE TO USER CRM_ANALYST;

USE ROLE SYSADMIN;

CREATE OR REPLACE DATABASE CRM_DB;
CREATE OR REPLACE SCHEMA CRM_DB.SHIPPING;
USE DATABASE CRM_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE EMPLOYEE (NAME VARCHAR);
INSERT INTO EMPLOYEE VALUES('Raghu Bengeri');


GRANT USAGE ON DATABASE CRM_dB TO ROLE CRM_ANALYST_ROLE;
GRANT ALL ON SCHEMA CRM_DB.SHIPPING TO ROLE CRM_ANALYST_ROLE;

CREATE OR REPLACE WAREHOUSE CRM_WH
     WITH WAREHOUSE_SIZE = 'XSMALL'
     AUTO_SUSPEND=300
     AUTO_RESUME= TRUE;

GRANT USAGE ON WAREHOUSE CRM_WH TO ROLE CRM_ANALYST_ROLE;

/*---------------------------------------------------
Create and load shipping table
------------------------------------------------*/
USE ROLE CRM_ANALYST_ROLE;
USE WAREHOUSE CRM_WH;
USE CRM_DB.SHIPPING;

CREATE OR REPLACE TABLE SHIPPING_INFO
(Account_ID VARCHAR(64),
 Shipment_Id varchar(64),
Shipping_State varchar(4),
Last_Modified_Date DATE,
Closed_Date DATE,
Priority VARCHAR(10),
Contact_Name VARCHAR(64),
SLA_Compliant_textBucket VARCHAR(10),
Shipmen_Account_Name VARCHAR(64),
Line_Haul_Carrier VARCHAR(64),
Product_Description VARCHAR(64),
Shipment_Name VARCHAR(64),
Created_Date DATE,
Profit_per_Order DECIMAL(10,4),
Cost_per_Ship  DECIMAL(10,4),
Estimated_Days_to_Destination INT );

-- Load shippings systems data from public S3 bucket to simulate ETL processes

--Use an external stage to load data from S3

CREATE OR REPLACE STAGE SHIPPING_DATA
url = 's3://snowflake-corp-se-workshop/VHOL_Snowflake_Salesforce/TCRM_V1/data';

--Load data by using the COPY command
COPY INTO SHIPPING_INFO FROM @SHIPPING_DATA/ FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' DATE_FORMAT = 'MM/DD/YY');

SELECT * FROM SHIPPING_INFO limit 10;
