/*__________________________
Snowflake and SalesForce


USE ROLE SECURITYADMIN;

CREATE OR REPLACE ROLE CRM_ANALYST_ROLE COMMENT='CRM_ANALYST_ROLE'
GRANT ROLE CRM_ANALYST_ROLE TO ROLE SYSADMIN;


CREATE OR REPLACE USER CRM_ANALYST  PASSWORD='TCRMSNOW123' 
    DEFAULT_ROLE=CRM_ANALYST_ROLE
    DEFAULT_WAREHOUSE=CRM_WH
    DEFAULT_NAMESPACE=CRB_DB_PUBLIC
    MUST_CHANGE_PASSWORD=FALSE
    COMMENT = 'CRM ANALYST';

GRANT ROLE CRM_ANALYST_ROLE TO USER CRM_ANALYST;

USE ROLE SYSADMIN;

CREATE OR REPLACE DATABASE CRM_DB;
CREATE OR REPLACE SCHEMA CRM_DB.SHIPPING;

GRANT USAGE ON DATABASE CRM_dB TO ROLE CRM_ANALYST_ROLE;
GRANT ALL ON SCHEMA CRM_DB.SHIPPING TO ROLE CRM_ANALYST_ROLE;

GRANT USAGE ON WAREHOUSE CRM_WH TO ROLE CRM_ANALYST_ROLE;

