USE ROLE ACCOUNTADMIN;
SHOW SHARES;


GRANT IMPORT share on ACCOUNT to CRM_ANALYST_ROLE;
GRANT CREATE database on ACCOUNT to CRM_ANALYST_ROLE;

USE ROLE CRM_ANALYST_ROLE;

USE WEATHERSOURCE.STANDARD_TILE;


SELECT * FROM WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY ORDER BY DATE_VALID_STD DESC LIMIT 1000;

SELECT * FROM WEATHERSOURCE.STANDARD_TILE.FORECAST_DAY ORDER BY DATE_VALID_STD DESC LIMIT 1000;

-- HISTORY POSTAL_CODE- MAX_TEMPERATURE_AIR_2M_F, MIN_TEMPERATURE_AIR_2M_F, TOT_PRECIPITATION_IN
-- FORECAST POSTAL_CODE - MAX_TEMPERATURE_AIR_2M_F, MIN_TEMPERATURE_AIR_2M_F, PROBABILITY_OF_PRECIPITATION_PCT

--Looks like we only have ZIP codes
--Let's see if we can use another Marketplace data set to give us states
--SafeGraph has State and ZIP code info in the Starbucks pattern listing

USE SAFEGRAPH_STARBUCKS.PUBLIC;

SELECT * FROM SAFEGRAPH_STARBUCKS.PUBLIC.PATTERNS LIMIT 1000;

--Great looks like we will be able to cover most States and Zips codes
--Let's create views to join the Weather Source and SafeGraph data for east use

USE CRM_DB.SHIPPING;

CREATE OR REPLACE VIEW WEATHER_HISTORICAL AS
    SELECT W.DATE_VALID_STD AS DATE, S.REGION AS STATE, MAX(W.MAX_TEMPERATURE_AIR_2M_F) AS MAX_TEMP,
            MIN(W.MIN_TEMPERATURE_AIR_2M_F) AS MIN_TEMP, MAX(W.TOT_PRECIPITATION_IN) AS PRECIPITATION,
            MAX(W.MAX_WIND_SPEED_10M_MPH) AS MAX_WIND
        FROM WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY W, SAFEGRAPH_STARBUCKS.PUBLIC.PATTERNS S
        WHERE W.POSTAL_CODE = S.POSTAL_CODE
        GROUP BY W.DATE_VALID_STD,S.REGION;


CREATE OR REPLACE VIEW WEATHER_FORECAST AS        
       SELECT W.DATE_VALID_STD AS DATE, S.REGION AS STATE, MAX(W.MAX_TEMPERATURE_AIR_2M_F) AS MAX_TEMP_F,
            MIN(W.MIN_TEMPERATURE_AIR_2M_F) AS MIN_TEMP_F, MAX(W.PROBABILITY_OF_PRECIPITATION_PCT) AS PRECIPITATION_PROB,
            MAX(W.MAX_WIND_SPEED_10M_MPH) AS MAX_WIND
        FROM WEATHERSOURCE.STANDARD_TILE.FORECAST_DAY W, SAFEGRAPH_STARBUCKS.PUBLIC.PATTERNS S
        WHERE W.POSTAL_CODE = S.POSTAL_CODE
        GROUP BY W.DATE_VALID_STD,S.REGION;


--How does weather impact our shipping?

SELECT S.*, WH.MAX_TEMP, WH.MIN_TEMP, WH.PRECIPITATION, WH.MAX_WIND
    FROM SHIPPING_INFO S LEFT JOIN WEATHER_HISTORICAL WH
    ON S.SHIPPING_STATE = WH.STATE AND TO_DATE(S.CREATED_DATE) = WH.DATE;
--We can create a view for users to get easier access to the information

CREATE OR REPLACE VIEW SHIP_WEATHER_HISTORY AS
    SELECT S.*, WH.MAX_TEMP, WH.MIN_TEMP, WH.PRECIPITATION, WH.MAX_WIND
    FROM SHIPPING_INFO S LEFT JOIN WEATHER_HISTORICAL WH
    ON S.SHIPPING_STATE = WH.STATE AND TO_DATE(S.CREATED_DATE) = WH.DATE;

